POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "Jackes Sparoú",
  "dateOfBirth": "1837-01-01",
  "gender": "male",
  "occupation": "pirate",
  "ssn": "123-45-6789"
}